Isbn website
roost-io/google_book_api pull request #5
Opened 2022-07-01 11:49 UTC by Priyanshii677

2022-07-01 12:38 UTC, mgdevstack requested changes

2022-07-01 12:38 UTC, mgdevstack commented on googlebookapi.yaml
> +  - name: tcp
```suggestion
  - name: ui-tcp
```

2022-07-01 12:38 UTC, mgdevstack commented on googlebookapi.yaml
>    - name: tcp
```suggestion
  - name: bookapi-tcp
```

2022-07-01 12:38 UTC, mgdevstack commented on ui/templates/hello.html
> +        <input
Just ISBN numbers are mentioned. Add `Examples:` xxxxxxxx , xxxxxxxxxx etc

2022-07-01 12:38 UTC, mgdevstack commented on ui/templates/hello.html
> +        window.location.href = " http://roost-worker:30045/books/" + y;
Host of the endpoint should be read from ENV["API_ENDPOINT"]

2022-07-01 12:38 UTC, mgdevstack commented on ui/templates/hello.html
> +        window.location.href = " http://roost-worker:30045/books/" + y;
JS should make and API call to get book details. And JSON response returned from the API should be displayed in the same UI page at the bottom as Book Detail. (No redirection to http://$HOST/books/)

2022-07-01 12:40 UTC, mgdevstack commented on ui/templates/hello.html
> +        window.location.href = " http://roost-worker:30045/books/" + y;
ENV["API_ENDPOINT"] can be configured in it's container section of googlebookapi.yaml

2022-07-06 07:07 UTC, harishagrawal commented
ui.exe is checked in .. 
Shouldn't this be getting created within the docker container

2023-01-06 08:26 UTC, harishagrawal approved these changes

2023-01-06 08:30 UTC, merged